"""empty message

Revision ID: 317d449569f6
Revises: b272ff544200
Create Date: 2016-04-26 22:12:15.147629

"""

# revision identifiers, used by Alembic.
revision = '317d449569f6'
down_revision = 'b272ff544200'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
