"""empty message

Revision ID: 353af210fcd7
Revises: 81ad604c5988
Create Date: 2016-04-13 21:08:09.258366

"""

# revision identifiers, used by Alembic.
revision = '353af210fcd7'
down_revision = '81ad604c5988'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###
