"""empty message

Revision ID: 8564ce404cc5
Revises: f87cfd5f6c83
Create Date: 2016-05-21 13:22:37.870722

"""

# revision identifiers, used by Alembic.
revision = '8564ce404cc5'
down_revision = 'f87cfd5f6c83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
