"""empty message

Revision ID: 9c35e3fe8b4f
Revises: 353af210fcd7
Create Date: 2016-04-13 21:08:54.777261

"""

# revision identifiers, used by Alembic.
revision = '9c35e3fe8b4f'
down_revision = '353af210fcd7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=64), nullable=True))
    ### end Alembic commands ###
