"""empty message

Revision ID: b272ff544200
Revises: 9c35e3fe8b4f
Create Date: 2016-04-24 20:55:21.508495

"""

# revision identifiers, used by Alembic.
revision = 'b272ff544200'
down_revision = '9c35e3fe8b4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
