"""empty message

Revision ID: e973e721fb4a
Revises: 8d7db0aaf175
Create Date: 2016-05-14 16:43:33.890772

"""

# revision identifiers, used by Alembic.
revision = 'e973e721fb4a'
down_revision = '8d7db0aaf175'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
